const Cards = [
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Самарканд",
    price: "204 000 000",
    title: "Chevrolet Onix 1.2 Turbo в наличии",
    id: "1",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "280 000",
    title: "7Saber Trucker Cap",
    id: "2",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "4 820 000",
    title: "Оригинальные кроссовки Nike Air Max Plus",
    id: "3",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "4 820 000",
    title: "Оригинальные кроссовки Nike Air Max 97",
    id: "4",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "4 500 000",
    title: "Apple Watch Series 8 - USA Non active",
    id: "5",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "320 000 000",
    title: "Лучший кроссовер Geely Monjaro Limited Edition",
    id: "6",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "5 599 000",
    title: "Стайлер для волос Dyson airwrap complete long",
    id: "7",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "280 000",
    title: "7Saber Trucker Cap",
    id: "8",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "2 599 000",
    title: "Оригинальные кроссовки Nike Air Max Plus",
    id: "9",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "2 599 000",
    title: "Chevrolet Onix 1.2 Turbo в наличии",
    id: "10",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "2 599 000",
    title: "Кепки Corneliani Diamond for him edition.",
    id: "11",
  },
  {
    image: "./images/card-img/Image(1).png",
    address: "г. Ташкент",
    price: "2 599 000",
    title: "Кепки Corneliani Diamond for him edition.",
    id: "12",
  },
];

export default Cards;
